#docker-compose.backup.yml
version: '3'
services:
  node-app:
    #restart: unless-stopped
    build: .
    ports:
      - "4000:3000"
    environment:
      - PORT=3000

  mongodb-node:
    image: mongo
    container_name: mongodb-node
    restart: unless-stopped
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-password1
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
