#docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx
    #restart: unless-stopped
    ports:
      - "8060:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongodb-node

  mongodb-node:
    image: mongo
    container_name: mongodb-node
    restart: unless-stopped
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-password1
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis

volumes:
  mongo-db:
